### ISSUE TITLE
Unable to run with docker-compose

### ISSUE THREAD

**Issue by jbm715** [projectcypress/cypress#899]
Attempting to run this locally using the specified docker-compose.yml on the v3.2.0 tag.

The changes I made
Dockerfile: `ENV RAILS_ENV development`
Dockerfile: `RUN su app -c 'bundle install --without test'`
docker-compose.yml: Removed `env_file: .env-prod`

Once the mongo and cypress containers start I run into errors where unicorn and the 4 delayed job works won't run with the following error: `runsv unable to start ./run file does not exist`. I checked the those run files do in fact exist in the context of those processes.

**Comment by rbclark** [comment]
If you do not modify the docker-compose.yml file at all you will be able to run the application. You will need to create a `.env-prod` file with the following contents:

```
DEVISE_SECRET_KEY=<insert rails secret key there>
SECRET_KEY_BASE=<insert rails secret key there>
```

You can generate a rails secret key using the following command:

`hexdump -n 64 -e '/1 "%02x"' -e '/64 "\n"' /dev/urandom`

Also I would suggest using the following docker-compose.yml file so you do not have to go through the whole build process:

```
version: "3"

services:
  cypress:
    image: projectcypress/cypress:release-latest
    environment:
      - MONGO_PORT_27017_TCP_ADDR=mongodb
      - MONGO_PORT_27017_TCP_PORT=27017
    ports:
      - "3000:3000"
    links:
      - mongodb:mongo
    env_file: .env-prod
    restart: unless-stopped
  mongodb:
    image: mongo:3.4.5
    volumes:
      - /data/db
    restart: unless-stopped
```
